{
 "title": "Blocky query",
 "tags": [
  "infra",
  "blocky"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "client_name",
    "label": "Client name",
    "query": "select distinct client_name from log_entries"
   },
   {
    "name": "response_type",
    "label": "Response type",
    "query": "select distinct response_type from log_entries"
   },
   { "name": "question", "label": "Domain (contains)" }
  ]
 },
 "panels": [
  {
   "title": "Query count by response type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT t.response_type, count(*) as cnt \r\nFROM log_entries t \r\nWHERE $__timeFilter(t.request_Ts) \r\n  AND t.response_type in ($response_type)\r\n  AND t.client_name in ($client_name)\r\n  AND (length('$question') = 0 or POSITION(lower('$question') in t.question_name) > 0)\r\nGROUP BY t.response_type"
    }
   ]
  },
  {
   "title": "Blocked by Blacklist",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT case when t.reason  like 'BLOCKED%' then regexp_replace(t.reason, '[^(]+\\(([^)]+)\\)', '\\1') else '' end AS metric,\r\n       count(t.reason) AS cnt\r\nFROM log_entries t\r\nWHERE t.response_type ='BLOCKED'\r\n  AND $__timeFilter(t.request_Ts)\r\n  AND t.client_name in ($client_name)\r\n  AND (length('$question') = 0 or POSITION(lower('$question') in t.question_name) > 0)\r\nGROUP BY metric"
    }
   ]
  },
  {
   "title": "Query count by client",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT t.client_name as metric, count(*) as cnt\r\nFROM log_entries t \r\nWHERE $__timeFilter(t.request_Ts) \r\n  AND t.response_type in ($response_type) \r\n  AND t.client_name in ($client_name) \r\n  AND (length('$question') = 0 or POSITION(lower('$question') in t.question_name) > 0)\r\nGROUP BY t.client_name\r\nORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "Top 20 effective TLD+1",
   "type": "barchart",
   "description": "Top 20 effective top level domain plus one more label",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT t.effective_tldp as metric, count(*) as value\r\nFROM log_entries t \r\nWHERE $__timeFilter(t.request_Ts) \r\n  AND t.response_type in ($response_type) \r\n  AND t.client_name in ($client_name) \r\n  AND (length('$question') = 0 or POSITION(lower('$question') in t.question_name) > 0)\r\nGROUP BY t.effective_tldp \r\nORDER BY count(*) DESC \r\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Top 20 queried domains",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT t.question_name as metric, count(*) as value\r\nFROM log_entries t \r\nWHERE $__timeFilter(t.request_Ts) \r\n  AND t.response_type in ($response_type) \r\n  AND t.client_name in ($client_name) \r\n  AND (length('$question') = 0 or POSITION(lower('$question') in t.question_name) > 0)\r\nGROUP BY t.question_name \r\nORDER BY count(*) DESC \r\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Queries number per client (30m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(t.request_Ts, '30m'),\n  t.client_name,\n  count(*) as c\nFROM log_entries t\nWHERE $__timeFilter(t.request_Ts)\n  AND t.response_type in ($response_type)\n  AND t.client_name in ($client_name)\n  AND (length('$question') = 0 or POSITION(lower('$question') in t.question_name) > 0)\nGROUP BY 1,2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Query duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  t.request_Ts as time,\n  t.duration_ms\nFROM log_entries t\nWHERE $__timeFilter(t.request_Ts)\n  AND t.response_type in ($response_type)\n  AND t.client_name in ($client_name) \n  AND (length('$question') = 0 or POSITION(lower('$question') in t.question_name) > 0)\nORDER BY request_ts"
    }
   ]
  },
  {
   "title": "Last queries",
   "type": "table",
   "description": "Last 100 queries, newest on top",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT t.request_Ts as \"time\", \n       t.client_ip as \"client IP\", \n       t.client_name as \"client name\", \n       t.duration_ms as \"duration in ms\", \n       t.response_type as \"response type\", \n       t.question_type as \"question type\", \n       t.question_name as \"question name\", \n       t.effective_tldp as \"effective TLD+1\", \n       t.answer as \"answer\" from log_entries t \nWHERE $__timeFilter(t.request_Ts)\n  AND t.response_type in ($response_type)\n  AND t.client_name in ($client_name)\n  AND (length('$question') = 0 or POSITION(lower('$question') in t.question_name) > 0)\nORDER BY t.request_Ts DESC\nLIMIT 100"
    }
   ]
  }
 ]
}