{
 "title": "Crowdsec bans",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ban map",
   "type": "geomap",
   "gridPos": { "h": 20, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "timeField": "start_at"
    }
   ]
  },
  {
   "title": "Bans per country",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "timeField": "start_at"
    }
   ]
  },
  {
   "title": "Bans per scenario",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "timeField": "start_at"
    }
   ]
  },
  {
   "title": "Ban count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "start_at"
    }
   ]
  },
  {
   "title": "Ban list",
   "type": "table",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "start_at"
    }
   ]
  }
 ]
}