{
 "title": "PI-Hole Exporter",
 "description": "This is a PI-Hole dashboard when using the https://github.com/eko/pihole-exporter Prometheus exporter",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "node",
    "query": "label_values(pihole_ads_blocked_today, hostname)"
   }
  ]
 },
 "panels": [
  { "title": "🍓PI-Hole", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pihole_status{hostname=~'$node'}",
     "legendFormat": "{{ legend }}"
    }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pihole_domains_being_blocked{hostname=~'$node'}"
    }
   ]
  },
  {
   "title": "Unique domains",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pihole_unique_domains{hostname=~'$node'}"
    }
   ]
  },
  {
   "title": "Top queries by domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "pihole_top_queries{hostname=~\"$node\"}",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Replies by type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "pihole_reply{hostname=~\"$node\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Top ads by domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "pihole_top_ads{hostname=~\"$node\"}",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "DNS queries all of types",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pihole_dns_queries_all_types{hostname=~'$node'}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "% ads blocked",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
   "targets": [
    {
     "expr": "pihole_ads_percentage_today{hostname=~'$node'}"
    }
   ]
  },
  {
   "title": "Ads blocked (today)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pihole_ads_blocked_today{hostname=~'$node'}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Queries cached/forwarded",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pihole_queries_cached{hostname=~'$node'}",
     "legendFormat": "Queries cached"
    },
    { "expr": "pihole_queries_forwarded", "legendFormat": "Queries forwarded" }
   ]
  },
  {
   "title": "DNS Query types",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "pihole_querytypes{hostname=~'$node'}",
     "legendFormat": "{{ type }}"
    },
    {}
   ]
  },
  {
   "title": "% of ads blocked",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "pihole_ads_percentage_today{hostname=~'$node'}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Top queries",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "pihole_top_queries{hostname=~'$node'}",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Top ads domains",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "pihole_top_ads{hostname=~'$node'}",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Forward destinations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "pihole_forward_destinations{hostname=~'$node'}",
     "legendFormat": "{{ destination }}"
    }
   ]
  },
  {
   "title": "Unique clients",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pihole_unique_clients{hostname=~'$node'}"
    }
   ]
  }
 ]
}