{
 "title": "Backup jobs",
 "tags": [ "backup" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "type",
    "query": {
     "query": "label_values(backup_job_status, type)"
    }
   },
   {
    "name": "repo",
    "query": {
     "query": "label_values(backup_job_status{type=~\"$type\"}, repo)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(backup_job_status{type=~\"$type\",repo=~\"$repo\"}, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Repo $repo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "repo" },
  {
   "title": "Status $host",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "backup_job_status{repo=~\"$repo\",host=~\"$host\",type=~\"$type\"}"
    }
   ]
  },
  {
   "title": "Age $host",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_job_start{repo=~\"$repo\",host=~\"$host\",type=~\"$type\"}"
    }
   ]
  },
  {
   "title": "Duration $host",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_job_duration{repo=~\"$repo\",host=~\"$host\",type=~\"$type\"}"
    }
   ]
  }
 ]
}