{
 "title": "Crowdsec LAPI Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "lapi",
    "query": {
     "query": "label_values(cs_info{crowdsec_role=\"lapi\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Agents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Agents Login",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "repeat": "query0",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cs_lapi_request_duration_seconds_bucket{exported_endpoint=\"/v1/watchers/login\", pod=\"$lapi\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heartbeat",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cs_lapi_request_duration_seconds_bucket{exported_endpoint=\"/v1/heartbeat\",pod=\"$lapi\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Decisions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Decisions GET (live)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cs_lapi_request_duration_seconds_bucket{exported_endpoint= \"/v1/decisions\", pod=\"$lapi\", method=~\"(GET)|(HEAD)\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Decisions GET (stream)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cs_lapi_request_duration_seconds_bucket{exported_endpoint= \"/v1/decisions/stream\", pod=\"$lapi\", method=~\"(GET)|(HEAD)\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Decisions DELETE",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cs_lapi_request_duration_seconds_bucket{exported_endpoint=~\"/v1/decisions.*\", pod=\"$lapi\", method=\"DELETE\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Alerts POST",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cs_lapi_request_duration_seconds_bucket{exported_endpoint=\"/v1/alerts\",pod=\"$lapi\",method=\"POST\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Alerts GET",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cs_lapi_request_duration_seconds_bucket{exported_endpoint=\"/v1/alerts\",pod=\"$lapi\",method=~\"(GET)|(HEAD)\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}