{
 "title": "Keepalived",
 "tags": [ "infra" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "iname",
    "query": "label_values(keepalived_vrrp_state, iname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(keepalived_up)" }
   ]
  },
  {
   "title": "Up (%)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(keepalived_up) / count(keepalived_up)"
    }
   ]
  },
  {
   "title": "Scripts KO",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(keepalived_script_status == 0)"
    }
   ]
  },
  {
   "title": "Scripts OK",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "count by (name) (keepalived_script_status == 1) / count by (name) (keepalived_script_status)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Interface : $iname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "iname" },
  {
   "title": "Master",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (instance) (keepalived_vrrp_state{iname = \"$iname\"} == 2))"
    }
   ]
  },
  {
   "title": "Backup",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (instance) (keepalived_vrrp_state{iname = \"$iname\"} == 1))"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (instance) (keepalived_vrrp_state{iname = \"$iname\"} == 3))"
    }
   ]
  }
 ]
}