{
 "title": "Nginx Sites",
 "tags": [
  "infra",
  "web",
  "nginx"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(nginx_up, instance)"
   },
   {
    "name": "namespace",
    "query": "label_values(nginxlog_http_response_count_total, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "NGinx Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(irate(nginxlog_http_response_count_total[2m])), 0.001)"
    }
   ]
  },
  {
   "title": "Success Rate (non-4|5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(nginxlog_http_response_count_total{status!~\"[4-5].*\"}[2m])) / sum(rate(nginxlog_http_response_count_total[2m]))"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(nginxlog_http_response_count_total{namespace=~\"$namespace\"}[2m])) by (namespace), 0.001)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Success Rate (non-4|5xx responses)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginxlog_http_response_count_total{namespace=~\"$namespace\",status!~\"[4-5].*\"}[2m])) by (namespace) / sum(rate(nginxlog_http_response_count_total{namespace=~\"$namespace\"}[2m])) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Percentile Response Times",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginxlog_http_response_time_seconds_hist_bucket{namespace=~\"$namespace\"}[2m])) by (le, namespace))",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginxlog_http_response_time_seconds_hist_bucket{namespace=~\"$namespace\"}[2m])) by (le, namespace))",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginxlog_http_response_time_seconds_hist_bucket{namespace=~\"$namespace\"}[2m])) by (le, namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  }
 ]
}