# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

settings = YAML.load_file 'Vagrantconfig.yaml'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = settings['common']['box_name']
	if settings['common']['box_version']
		config.vm.box_version  = settings['common']['box_version']
	end
	
	config.ssh.insert_key = false
	if Vagrant.has_plugin?("vagrant-vbguest")
    	config.vbguest.auto_update = false
	end
	
	####################
	#      Nodes       #
	####################
	settings['nodes'].each do |node_conf|
		config.vm.define node_conf['name'] do |node|			
			node.vm.provider :virtualbox do |vb|
				vb.customize ["modifyvm", :id, "--ioapic", "on"]
				vb.customize ["modifyvm", :id, "--memory", node_conf['memory']]
				vb.customize ["modifyvm", :id, "--cpus", node_conf['cpu']]
				vb.customize ["modifyvm", :id, "--cpuexecutioncap", node_conf['cpu_execution_cap']]
				
				docker_disk_path = '.vagrant/' + node_conf['name'] + '_docker.vdi'
				unless File.exist?(docker_disk_path)
					vb.customize ['createmedium', '--filename', docker_disk_path, '--size', node_conf['docker_disk_size']]
				end
				vb.customize ['storageattach', :id,  '--storagectl', settings['common']['sata_controller_name'], '--port', 1, '--device', 0, '--type', 'hdd', '--medium', docker_disk_path]

				data_disk_path = '.vagrant/' + node_conf['name'] + '_data.vdi'
				unless File.exist?(data_disk_path)
					vb.customize ['createmedium', '--filename', data_disk_path, '--size', node_conf['data_disk_size']]
				end
				vb.customize ['storageattach', :id,  '--storagectl', settings['common']['sata_controller_name'], '--port', 2, '--device', 0, '--type', 'hdd', '--medium', data_disk_path]
			end
			
			node.vm.network "private_network", ip: node_conf['ip']
			node.vm.provision "shell", path: "init_new_node.sh", args: "node", keep_color: true
			node.vm.provision "shell", path: "up_node.sh", run: "always", keep_color: true
		end
	end

	####################
	#    Controller    #
	####################
	controller_conf = settings['controller']
	config.vm.define controller_conf['name'] do |controller|
		controller.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--ioapic", "on"]
			vb.customize ["modifyvm", :id, "--memory", controller_conf['memory']]
			vb.customize ["modifyvm", :id, "--cpus", controller_conf['cpu']]
				
			docker_disk_path = '.vagrant/' + controller_conf['name'] + '_docker.vdi'
			unless File.exist?(docker_disk_path)
				vb.customize ['createmedium', '--filename', docker_disk_path, '--size', controller_conf['docker_disk_size']]
			end
			vb.customize ['storageattach', :id,  '--storagectl', settings['common']['sata_controller_name'], '--port', 1, '--device', 0, '--type', 'hdd', '--medium', docker_disk_path]

			data_disk_path = '.vagrant/' + controller_conf['name'] + '_data.vdi'
			unless File.exist?(data_disk_path)
				vb.customize ['createmedium', '--filename', data_disk_path, '--size', controller_conf['data_disk_size']]
			end
			vb.customize ['storageattach', :id,  '--storagectl', settings['common']['sata_controller_name'], '--port', 2, '--device', 0, '--type', 'hdd', '--medium', data_disk_path]
		end
		
		controller.vm.network "private_network", ip: controller_conf['ip']
		controller.vm.synced_folder "../", "/opt/provision", type: "virtualbox"
		controller.vm.provision "shell", path: "init_new_node.sh", args: "ansible", keep_color: true
		controller.vm.provision "shell", path: "ansible_provisioning.sh", keep_color: true
		controller.vm.provision "shell", path: "up_node.sh", run: "always", keep_color: true
	end
end
