version: 0.1
log:
    fields:
        service: docker-registry
storage:
    cache:
        blobdescriptor: inmemory
    filesystem:
        rootdirectory: /var/lib/registry
    delete:
        enabled: true
auth:
    htpasswd:
        realm: basic-realm
        path: /etc/docker/registry/htpasswd
health:
    storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
http:
    addr: :5443
    secret: ENC[AES256_GCM,data:77Ec6MRtJBdAhLGJ2LFub9WsIy7ho1FLkb7AzppiBLM=,iv:CWSFbaJnsAhPgfEUfA+Bv3MOoHIj9NRnBFbeymUfx3U=,tag:n7AjgvseR6wUML3h0nPM9w==,type:str]
    tls:
        certificate: /certs/tls.crt
        key: /certs/tls.key
    headers:
        X-Content-Type-Options:
            - nosniff
    debug:
        addr: :5001
        prometheus:
            enabled: true
            path: /metrics
notifications:
    endpoints:
        - name: docker-registry-ui
          url: http://docker-registry-ui.infra-docker-registry-ui.svc.cluster.local:8000/event-receiver
          headers:
            Authorization:
                - ENC[AES256_GCM,data:d7fT12pfxqFswgrC74qb0Fya5aD7YJSAirL+PaknXWgetLU6b2sY,iv:x2qXfk8pDkd/kNlDfmtWmcib+7YsIgiM/x3dpXYn1Aw=,tag:q2I21UGMXF4dDD80npgT4Q==,type:str]
          timeout: 1s
          threshold: 5
          backoff: 10s
          ignoredmediatypes:
            - application/octet-stream
sops:
    age:
        - recipient: age1ykc9cp7e7sylr09ldufwd337h6kvghn8ga250unudvxxlaczpuzsv04rqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUV1NHYXJNMFd6T2h2N0VZ
            R0lNU2REQWdSTndqQUNTc0p5TmJNVXlGZ1QwCi9VQmxtNlFvOWlFNmEzeWcybG96
            dVZGZ2dJQngxNjVaR1o0M1RjSlBLd0UKLS0tIGl4LzAwS3c2UnhNRFl3U1VWQUwx
            cFJxU1B4eGJRS0NVUXRqWWFsclVPSUkKkEe56eoBl4xnWsLxLjRb18xkHHUjWU9n
            Xn2XpYoKHRImeDdMg8QbdHM8kD5v1OM7bby0LmG+K1p5FjAlttsl8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T21:15:44Z"
    mac: ENC[AES256_GCM,data:0XXflo+jefFH6Pz1df8Sipys1nyHnJHcI8OgRgc10RsAy4RYt7zt/gx4494fn5AoGhKn9XpTmI1xSPDb7VMpDctj1tMkyMdKxzyn9Yqm+PTiG3/0D6qZyDlEP1G/Aw+VhFWyoBn/FccK5RJM7mGQYVZm53c5meVKC+xNxqz0f40=,iv:cngfwRvcIXqDynCh4PyPMD8UmZ7oSlT8ZIicZrrY+hU=,tag:kH/5CiBCSMKKVJW7OKtKhw==,type:str]
    encrypted_regex: ^(secret|Authorization)$
    version: 3.12.2
