{
 "title": "UPS",
 "tags": [
  "infra",
  "ups"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Current Time On Battery",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "apcupsd_battery_time_on_seconds"
    }
   ]
  },
  {
   "title": "Cumulative Time On Battery",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "apcupsd_battery_cumulative_time_on_seconds_total"
    }
   ]
  },
  {
   "title": "Battery Time Left",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "apcupsd_battery_time_left_seconds"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "apcupsd_battery_charge_percent" }
   ]
  },
  {
   "title": "UPS Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "apcupsd_ups_load_percent" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "apcupsd_battery_volts" },
    { "expr": "apcupsd_battery_nominal_volts" }
   ]
  },
  {
   "title": "AC Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "apcupsd_line_nominal_volts" },
    { "expr": "apcupsd_line_volts" }
   ]
  }
 ]
}