{
 "title": "GitLab Omnibus - Redis",
 "description": "GitLab Omnibus dashboard for Redis servers",
 "tags": [
  "redis",
  "Gitlab"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(up{job=\"gitlab-redis\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(time() - redis_start_time_seconds{job=\"gitlab-redis\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(\n  avg_over_time(redis_connected_clients{job=\"gitlab-redis\", instance=~\"$instance\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Commands Executed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(redis_commands_processed_total{job=\"gitlab-redis\", instance=~\"$instance\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Hits, Misses per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(redis_keyspace_hits_total{job=\"gitlab-redis\", instance=~\"$instance\"}[$__interval])\n)",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(\n  rate(redis_keyspace_misses_total{job=\"gitlab-redis\", instance=~\"$instance\"}[$__interval])\n)",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{job=\"gitlab-redis\", instance=~\"$instance\"}",
     "legendFormat": "used - {{instance}}"
    },
    {
     "expr": "redis_config_maxmemory{job=\"gitlab-redis\", instance=~\"$instance\"} > 0",
     "legendFormat": "max - {{instance}}"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{job=\"gitlab-redis\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{job=\"gitlab-redis\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(redis_net_input_bytes_total{job=\"gitlab-redis\", instance=~\"$instance\"}[$__interval])\n)",
     "legendFormat": "In"
    },
    {
     "expr": "sum(\n  rate(redis_net_output_bytes_total{job=\"gitlab-redis\", instance=~\"$instance\"}[$__interval])\n)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (\n  rate(redis_commands_total{job=\"gitlab-redis\", instance=~\"$instance\"}[$__interval])\n) > 0",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_db_keys{job=\"gitlab-redis\", instance=~\"$instance\"} - redis_db_keys_expiring{job=\"gitlab-redis\", instance=~\"$instance\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum(redis_db_keys_expiring{job=\"gitlab-redis\", instance=~\"$instance\"})",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (db) (\n  redis_db_keys{job=\"gitlab-redis\", instance=~\"$instance\"}\n)",
     "legendFormat": "{{ db }} "
    }
   ]
  }
 ]
}