{
 "title": "GitLab Omnibus - Overview",
 "description": "GitLab Omnibus Dashboard (>= 10.3)",
 "tags": [ "gitlab" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(up{job=~\"gitlab.*\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Unicorn Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(up{job=~\"gitlab-(rails|unicorn)\",instance=~\"($node):.*\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Postgres Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(pg_up{instance=~\"($node):.*\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Sidekiq Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(up{job=\"gitlab-sidekiq\",instance=~\"($node):.*\"}[$__interval])\n) "
    }
   ]
  },
  {
   "title": "Workhorse Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(up{job=\"gitlab-workhorse\",instance=~\"($node):.*\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Redis Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(redis_up{instance=~\"$node:9121\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Gitaly Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(up{job=\"gitaly\",instance=~\"($node):.*\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Sidekiq Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  avg_over_time(\n    sidekiq_queue_size{instance=~\"($node):.*\"}[$__interval]\n  )\n)",
     "legendFormat": "Queued"
    }
   ]
  },
  {
   "title": "Workhorse Latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(gitlab_workhorse_http_request_duration_seconds_bucket{instance=~\"($node):9229\"}[$__interval])\n)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}