{
 "title": "GlusterFS Volumes",
 "tags": [
  "infra",
  "gluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Volume",
    "label": "Volume",
    "query": "label_values(gluster_volume_up, volume)"
   }
  ]
 },
 "panels": [
  { "title": "Volume Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gluster_volume_up{volume = \"$Volume\"}"
    }
   ]
  },
  {
   "title": "Capacity Utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gluster:volume_capacity_used_bytes_total:sum{volume='$Volume'} / gluster:volume_capacity_total_bytes:sum{volume='$Volume'}"
    }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gluster:volume_capacity_total_bytes:sum{volume='$Volume'} - gluster:volume_capacity_used_bytes_total:sum{volume='$Volume'}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum (gluster_volume_profile_total_reads_interval{volume='$Volume'}) + sum(gluster_volume_profile_total_writes_interval{volume='$Volume'}))/max(gluster_volume_profile_duration_secs_interval{volume='$Volume'})"
    }
   ]
  },
  {
   "title": "Capacity Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "gluster:volume_capacity_used_bytes_total:sum{volume='$Volume'}",
     "legendFormat": "{{$Volume}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum (gluster_volume_profile_total_reads_interval{volume='$Volume'}) + sum(gluster_volume_profile_total_writes_interval{volume='$Volume'}))/max(gluster_volume_profile_duration_secs_interval{volume='$Volume'})",
     "legendFormat": "{{$Volume}}"
    }
   ]
  },
  {
   "title": "LVM Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "LVM Thin Pool Metadata %",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*(gluster_thinpool_metadata_used_bytes{volume='$Volume'} / gluster_thinpool_metadata_total_bytes{volume='$Volume'})",
       "legendFormat": "{{thinpool_name}}"
      }
     ]
    },
    {
     "title": "LVM Thin Pool Data Usage  %",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100*(gluster_thinpool_data_used_bytes{volume='$Volume'} / gluster_thinpool_data_total_bytes{volume='$Volume'})",
       "legendFormat": "{{thinpool_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bricks (Volume Subcomponent) Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "Bricks-Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gluster_volume_brick_count{volume='$Volume'}"
    }
   ]
  },
  {
   "title": "Bricks-Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (gluster_brick_up{volume='$Volume'} == 1)"
    }
   ]
  },
  {
   "title": "Bricks-Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(gluster_brick_up{volume='$Volume'}) - count (gluster_brick_up{volume='$Volume'} == 1)"
    }
   ]
  },
  {
   "title": "Capacity Utilization-Average",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (gluster_brick_capacity_used_bytes{volume='$Volume'} / gluster_brick_capacity_bytes_total{volume='$Volume'})"
    }
   ]
  },
  {
   "title": "Capacity Utilization-Min",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min (gluster_brick_capacity_used_bytes{volume='$Volume'} / gluster_brick_capacity_bytes_total{volume='$Volume'})"
    }
   ]
  },
  {
   "title": "Capacity Utilization-Max",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max (gluster_brick_capacity_used_bytes{volume='$Volume'} / gluster_brick_capacity_bytes_total{volume='$Volume'})"
    }
   ]
  },
  {
   "title": "Brick Usage < 80%",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count((gluster_brick_capacity_used_bytes{volume='$Volume'} / gluster_brick_capacity_bytes_total{volume='$Volume'}) < 0.8)"
    }
   ]
  },
  {
   "title": "Brick Usage > 80% < 90%",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count((gluster_brick_capacity_used_bytes{volume='$Volume'} / gluster_brick_capacity_bytes_total{volume='$Volume'}) < 0.9) - count((gluster_brick_capacity_used_bytes{volume='$Volume'} / gluster_brick_capacity_bytes_total{volume='$Volume'}) < 0.8)"
    }
   ]
  },
  {
   "title": "Brick Usage > 90%",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(gluster_brick_capacity_used_bytes{volume='$Volume'}) - count((gluster_brick_capacity_used_bytes{volume='$Volume'} / gluster_brick_capacity_bytes_total{volume='$Volume'}) < 0.9)"
    }
   ]
  },
  {
   "title": "IOPS - Avg",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 22 },
   "format": "locale",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg((gluster_volume_profile_total_reads_interval{volume='$Volume'} + gluster_volume_profile_total_writes_interval{volume='$Volume'}) /gluster_volume_profile_duration_secs_interval{volume='$Volume'})"
    }
   ]
  },
  {
   "title": "IOPS - Min",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 22 },
   "format": "locale",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min((gluster_volume_profile_total_reads_interval{volume='$Volume'} + gluster_volume_profile_total_writes_interval{volume='$Volume'}) /gluster_volume_profile_duration_secs_interval{volume='$Volume'})"
    }
   ]
  },
  {
   "title": "IOPS - Max",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 22 },
   "format": "locale",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max((gluster_volume_profile_total_reads_interval{volume='$Volume'} + gluster_volume_profile_total_writes_interval{volume='$Volume'}) /gluster_volume_profile_duration_secs_interval{volume='$Volume'})"
    }
   ]
  },
  {
   "title": "Heal Counts-Total Files",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (gluster_volume_heal_count{volume='$Volume'})"
    }
   ]
  },
  {
   "title": "Heal Counts-Files in Split-Brain",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (gluster_volume_split_brain_heal_count{volume='$Volume'})"
    }
   ]
  },
  { "title": "Volume Profiling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Top file operation",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(sum(gluster_volume_profile_fop_avg_latency{volume='$Volume', fop!=''})by (fop))"
    }
   ]
  },
  {
   "title": "File Operations For Locks Trends",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(gluster_volume_profile_fop_total_hits_on_aggregated_fops{volume='$Volume',fop='LOCK_OPS'}) by (volume)"
    }
   ]
  },
  {
   "title": "File Operations for Read/Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(gluster_volume_profile_fop_total_hits_on_aggregated_fops{volume='$Volume',fop='READ_WRITE_OPS'}) by (volume)"
    }
   ]
  },
  {
   "title": "File Operations for Inode Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(gluster_volume_profile_fop_total_hits_on_aggregated_fops{volume='$Volume',fop='INODE_OPS'}) by (volume)"
    }
   ]
  },
  {
   "title": "File Operations for Entry Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(gluster_volume_profile_fop_total_hits_on_aggregated_fops{volume='$Volume',fop='ENTRY_OPS'}) by (volume)"
    }
   ]
  }
 ]
}