#!/bin/sh
set -e ; # Have script exit in the event of a failed command.

source /config/add-policy

## Create the policies
#cat <<EOF > /tmp/policy_0.json
#{
#  "Version": "2012-10-17",
#  "Statement": [
#    {
#      "Effect": "Allow",
#      "Action": [
#        "s3:ListBucket",
#        "s3:GetObject"
#      ],
#      "Resource": [
#        "arn:aws:s3:::bucket1"
#      ] 
#    }
#  ]
#}
#EOF
#
#createPolicy mypolicy policy_0
