#!/bin/sh
set -e ; # Have script exit in the event of a failed command.

source /config/add-user

## Create the users
#echo accessKey > $MINIO_ACCESSKEY_SECRETKEY_TMP
#echo secretKey >> $MINIO_ACCESSKEY_SECRETKEY_TMP
#createUser readwrite
