{
 "title": "Backup task detail",
 "tags": [ "backup" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "repo",
    "query": {
     "query": "label_values(backup_task_status, repo)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(backup_task_status{repo=\"$repo\"}, host)"
    }
   },
   {
    "name": "path",
    "query": {
     "query": "label_values(backup_task_status{host=\"$host\", repo=\"$repo\"}, path)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_task_status{host=\"$host\", repo=\"$repo\", path=\"$path\"}"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_task_start{host=\"$host\", repo=\"$repo\", path=\"$path\"}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_task_duration{host=\"$host\", repo=\"$repo\", path=\"$path\"}"
    }
   ]
  },
  { "title": "Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Added",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "backup_task_added_bytes{host=\"$host\", repo=\"$repo\", path=\"$path\"}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "backup_task_total_bytes{host=\"$host\", repo=\"$repo\", path=\"$path\"}"
    }
   ]
  },
  { "title": "Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "backup_task_files{host=\"$host\", repo=\"$repo\", path=\"$path\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Directories",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "backup_task_dirs{host=\"$host\", repo=\"$repo\", path=\"$path\"}",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}