{
 "title": "Backup Restic repos maintenance",
 "tags": [ "backup" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "repo",
    "query": {
     "query": "label_values(backup_maintenance_status, repo)"
    }
   },
   {
    "name": "operation",
    "query": {
     "query": "label_values(backup_maintenance_status, operation)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Operation $operation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "operation" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_maintenance_status{repo=\"$repo\", operation=\"$operation\"}"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_maintenance_start{repo=\"$repo\", operation=\"$operation\"}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_maintenance_duration{repo=\"$repo\", operation=\"$operation\"}"
    }
   ]
  }
 ]
}