{
 "title": "ZoneMTA",
 "tags": [
  "infra",
  "mail",
  "zone-mta"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Received messages rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(zonemta_message_push[1m]))",
     "legendFormat": "Accepted"
    },
    {
     "expr": "sum(rate(zonemta_message_drop[1m]))",
     "legendFormat": "Dropped"
    }
   ]
  },
  {
   "title": "Blacklisting",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "zonemta_blacklisted" }
   ]
  },
  {
   "title": "Sent messages rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(zonemta_delivery_status{status=\"delivered\"}[1m]))",
     "legendFormat": "Delivered"
    },
    {
     "expr": "sum by (status) (rate(zonemta_delivery_status{status=\"deferred\"}[1m]))",
     "legendFormat": "Deferred"
    },
    {
     "expr": "sum by (status) (rate(zonemta_delivery_status{status=\"rejected\"}[1m]))",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Blacklisting",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zonemta_blacklisted",
     "legendFormat": "Hosts that blacklist a localIP address"
    }
   ]
  },
  {
   "title": "Queue size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (zonemta_queue_size{type=\"deferred\"})",
     "legendFormat": "Deferred"
    },
    {
     "expr": "sum by (type) (zonemta_queue_size{type=\"queued\"})",
     "legendFormat": "Queued"
    }
   ]
  },
  {
   "title": "Delivered messages in the last hour",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "increase (zonemta_delivery_status{status=\"delivered\"}[1h])"
    }
   ]
  }
 ]
}